'use strict';
/* Real 2026-27 squads (fa.wikipedia / en.wikipedia verified names).
 * price = tenths of a million (65 = 6.5m). Budget: 100m.
 * Pricing criteria (documented in README):
 *  - club tier 5 (Big 4): base GK 4.5, DEF 4.5, MID 5.5, FWD 5.5
 *  - tier 4: -0.5 each; tier 3: -1; tier 2: -1.5
 *  - star multiplier applied per player reputation (national team, foreign star, top scorer)
 *  - floor 4.0 (budget enablers), ceiling 13.0
 * Format: [fa_name, en_name, pos, priceTenths, isForeign]
 */
module.exports = {
  persepolis: [
    ['پیام نیازمند', 'Payam Niazmand', 'GKP', 55, 0],
    ['حسین اینتی‌زاری', 'Hossein Entezari', 'GKP', 40, 0],
    ['علیرضا اژدری', 'Alireza Azhdari', 'GKP', 40, 0],
    ['محمدحسین کنعانی‌زادگان', 'Hossein Kanaanizadegan', 'DEF', 62, 0],
    ['مرتضی پورعلی‌گنجی', 'Morteza Pouraliganji', 'DEF', 55, 0],
    ['میلاد محمدی', 'Milad Mohammadi', 'DEF', 58, 0],
    ['دانیال گرا', 'Daniel Gera', 'DEF', 50, 1],
    ['امیرعلی صادقی', 'Amirali Sadeghi', 'DEF', 45, 0],
    ['سعید مهری', 'Saeid Mehri', 'DEF', 42, 0],
    ['اوستون ارونوف', 'Oston Urunov', 'MID', 85, 1],
    ['مارکو باکیچ', 'Marko Bakic', 'MID', 70, 1],
    ['محمدامین کاظمیان', 'Mohammadamin Kazemian', 'MID', 62, 0],
    ['رضا شکاری', 'Reza Shekari', 'MID', 55, 0],
    ['محمد عمری', 'Mohammad Omri', 'MID', 50, 0],
    ['محمدحسین صادقی', 'Mohammadhossein Sadeghi', 'MID', 48, 0],
    ['محمدمهدی موهبی', 'Mohammad Mehdi Mohebi', 'MID', 60, 0],
    ['علی علیپور', 'Ali Alipour', 'FWD', 85, 0],
    ['ایگور سرگیف', 'Igor Sergeev', 'FWD', 72, 1],
    ['تیوی بیفوما', 'Thievy Bifouma', 'FWD', 75, 1],
    ['ابوالفضل بابایی', 'Abolfazl Babaei', 'FWD', 45, 0]
  ],
  esteghlal: [
    ['آنتونیو آدان', 'Antonio Adan', 'GKP', 60, 1],
    ['حبیب فرعباسی', 'Habib Farabbasi', 'GKP', 45, 0],
    ['محمدرضا زربس', 'Mohammadreza Zerbesht', 'GKP', 40, 0],
    ['رستم آشورماتوف', 'Rustam Ashurmatov', 'DEF', 58, 1],
    ['صالح حردانی', 'Saleh Hardani', 'DEF', 55, 0],
    ['عارف آقاسی', 'Aref Aghasi', 'DEF', 52, 0],
    ['ابوالفضل ذلیخایی', 'Abolfazl Zalikhaei', 'DEF', 45, 0],
    ['روزبه چشمی', 'Rouzbeh Cheshmi', 'DEF', 60, 0],
    ['محمدحسین اسلامی', 'Mohammadhossein Eslami', 'DEF', 48, 0],
    ['جلال‌الدین ماشاریپوف', 'Jaloliddin Masharipov', 'MID', 75, 1],
    ['امیرمحمد رزاقی‌نیا', 'Amirmohammad Razaghinia', 'MID', 55, 0],
    ['مهران احمدی', 'Mehran Ahmadi', 'MID', 45, 0],
    ['اسماعیل قلی‌زاده', 'Esmail Gholizadeh', 'MID', 58, 0],
    ['دیدیه ندونگ', 'Didier Ndong', 'MID', 62, 1],
    ['مونیر الحدادی', 'Munir El Haddadi', 'MID', 80, 1],
    ['یاسر آسانی', 'Jasir Asani', 'MID', 85, 1],
    ['سعید سحرخیزان', 'Saeid Saharkhizan', 'FWD', 70, 0],
    ['داکنز نازون', 'Duckens Nazon', 'FWD', 68, 1],
    ['علیرضا کوشکی', 'Alireza Koushki', 'FWD', 48, 0],
    ['محمدرضا آزادی', 'Mohammadreza Azadi', 'FWD', 50, 0]
  ],
  tractor: [
    ['علیرضا بیرانوند', 'Alireza Beiranvand', 'GKP', 65, 0],
    ['محمدرضا انصاری', 'Mohammadreza Ansari', 'GKP', 42, 0],
    ['شجاع خلیل‌زاده', 'Shojae Khalilzadeh', 'DEF', 62, 0],
    ['فرشاد فرجی', 'Farshad Faraji', 'DEF', 55, 0],
    ['محمد نادری', 'Mohammad Naderi', 'DEF', 52, 0],
    ['محمد دانشگر', 'Mohammad Daneshgar', 'DEF', 50, 0],
    ['صادق محرمی', 'Sadeq Moharrami', 'DEF', 55, 0],
    ['مهدی شیری', 'Mehdi Shiri', 'DEF', 45, 0],
    ['تیبور هالیلوویچ', 'Tibor Halilovic', 'MID', 72, 1],
    ['ایگور پستونسکی', 'Igor Postonjski', 'MID', 65, 1],
    ['عادل‌جان همراه‌بکوف', 'Odiljon Hamrobekov', 'MID', 62, 1],
    ['مهدی حسینی', 'Mehdi Hosseini', 'MID', 48, 0],
    ['کرار نماری', 'Karar Namar', 'MID', 55, 1],
    ['هادی حبیبی‌نژاد', 'Hadi Habibinejad', 'MID', 42, 0],
    ['امیرحسین حسین‌زاده', 'Amirhossein Hosseinzadeh', 'FWD', 95, 0],
    ['تومیسلاو اشترکالی', 'Tomislav Strkalj', 'FWD', 80, 1],
    ['شهریار مغانلو', 'Shahriyar Moghanlou', 'FWD', 68, 0],
    ['مهدی ترابی', 'Mehdi Torabi', 'FWD', 75, 0]
  ],
  sepahan: [
    ['حسین حسینی', 'Hossein Hosseini', 'GKP', 55, 0],
    ['پایام رئیسی', 'Payam Raeisi', 'GKP', 42, 0],
    ['آرمین سهرابیان', 'Arman Sohrabian', 'DEF', 52, 0],
    ['آریا شفیع‌دوست', 'Aria Shafiedoust', 'DEF', 48, 0],
    ['محمدامین حزباوی', 'Mohammadamin Hazbavi', 'DEF', 50, 0],
    ['آریا یوسفی', 'Aria Yousefi', 'DEF', 45, 0],
    ['هادی محمدی', 'Hadi Mohammadi', 'DEF', 48, 0],
    ['احسان حاج‌صفی', 'Ehsan Hajsafi', 'MID', 65, 0],
    ['ریکاردو آلوز', 'Ricardo Alves', 'MID', 68, 1],
    ['محمد کریمی', 'Mohammad Karimi', 'MID', 65, 0],
    ['عارف حاجی‌عیدی', 'Aref Hajieidi', 'MID', 48, 0],
    ['محمدمهدی لطفی', 'Mohammad Mehdi Lotfi', 'MID', 50, 0],
    ['امیرحسین جلالی‌وند', 'Amirhossein Jalalivand', 'MID', 45, 0],
    ['کاوه رضایی', 'Kaveh Rezaei', 'FWD', 80, 0],
    ['علی خدادادی', 'Ali Khodadadi', 'FWD', 62, 0],
    ['کسری طاهری', 'Kasra Taheri', 'FWD', 55, 0],
    ['رضا جعفری', 'Reza Jafari', 'FWD', 48, 0]
  ],
  foolad: [
    ['حامد لک', 'Hamed Lak', 'GKP', 50, 0],
    ['علیرضا رضایی', 'Alireza Rezaei', 'GKP', 40, 0],
    ['رامین رضاییان', 'Ramin Rezaeian', 'DEF', 58, 0],
    ['محمد قریشی', 'Mohammad Ghorashi', 'DEF', 45, 0],
    ['سینا اصغرپور', 'Sina Asgharpour', 'DEF', 42, 0],
    ['امیرحسین جوادی', 'Amirhossein Javadi', 'DEF', 40, 0],
    ['ساسان انصاری', 'Sasan Ansari', 'MID', 55, 0],
    ['میلاد سرلک', 'Milad Sarlak', 'MID', 52, 0],
    ['امید حامدی‌فر', 'Omid Hamedifar', 'MID', 48, 0],
    ['فرشاد احمدزاده', 'Farshad Ahmadzadeh', 'MID', 55, 0],
    ['وحید امیری', 'Vahid Amiri', 'MID', 50, 0],
    ['گوستاوو بلانکو', 'Gustavo Blanco', 'MID', 58, 1],
    ['امیرحسین جولانی', 'Amirhossein Jolani', 'FWD', 55, 0],
    ['احسان محروقی', 'Ehsan Mahrouqi', 'FWD', 48, 0],
    ['متئوس کاستا', 'Matheus Costa', 'FWD', 50, 1],
    ['میلاد باغ‌جباری', 'Milad Baghjebbeh', 'FWD', 42, 0]
  ],
  golgohar: [
    ['فرزین گروسیان', 'Farzin Garousian', 'GKP', 48, 0],
    ['حسین کاوه', 'Hossein Kaveh', 'GKP', 40, 0],
    ['پدرام قاضی‌پور', 'Pedram Ghazipour', 'DEF', 48, 0],
    ['امیر جعفری', 'Amir Jafari', 'DEF', 45, 0],
    ['مجتبی نجاریان', 'Mojtaba Najarian', 'DEF', 42, 0],
    ['مسیح زاهدی', 'Masih Zahedi', 'DEF', 40, 0],
    ['علی‌اصغر عاشوری', 'Aliasghar Ashouri', 'MID', 52, 0],
    ['احمدرضا زنده‌روح', 'Ahmadreza Zendehrouh', 'MID', 55, 0],
    ['امید عالیشاه', 'Omid Alishah', 'MID', 58, 0],
    ['مجتبی فخریان', 'Mojtaba Fakhriyan', 'MID', 48, 0],
    ['سهیل صحرایی', 'Sohil Sahraei', 'MID', 45, 0],
    ['محمدعرفان معصومی', 'Mohammaderfan Masoumi', 'MID', 42, 0],
    ['مجید علیاری', 'Majid Aliyari', 'FWD', 60, 0],
    ['محمد علی‌نژاد', 'Mohammad Alinejad', 'FWD', 48, 0],
    ['لوی بن حسین', 'Louay Ben Hassine', 'FWD', 55, 1],
    ['کیوان چرم‌دسته', 'Keyvan Charmdoust', 'FWD', 40, 0]
  ],
  zobahan: [
    ['داوود نوشی‌صوفیانی', 'Davoud Noushi Soufiani', 'GKP', 48, 0],
    ['سجاد غفاری', 'Sajjad Ghaffari', 'GKP', 40, 0],
    ['سیدمحمد حسینی', 'Seyyed Mohammad Hosseini', 'DEF', 48, 0],
    ['بهنام تیموریان', 'Behnam Timorian', 'DEF', 45, 0],
    ['شاهین طاهرخانی', 'Shahin Taherkhani', 'DEF', 42, 0],
    ['حسین جرگه', 'Hossein Jargeh', 'DEF', 40, 0],
    ['جلال‌الدین علی‌محمدی', 'Jalaleddin Alimohammadi', 'MID', 50, 0],
    ['پویا مختاری', 'Pouya Mokhtari', 'MID', 45, 0],
    ['نیما انتظاری', 'Nima Entezari', 'MID', 42, 0],
    ['حسین صفری', 'Hossein Safarier', 'MID', 40, 0],
    ['فرشید اسماعیلی', 'Farshid Esmaeili', 'MID', 50, 0],
    ['دژن زایموویچ', 'Dzenan Zajmovic', 'FWD', 62, 1],
    ['رحمان جعفری', 'Rahman Jafari', 'FWD', 48, 0],
    ['علی اسلامی', 'Ali Eslami', 'FWD', 42, 0]
  ],
  malavan: [
    ['افشار صداقت', 'Afshar Sedaghat', 'GKP', 45, 0],
    ['پرهام قناد', 'Parham Ghanad', 'GKP', 40, 0],
    ['مهیار زحمتکش', 'Mahyar Zahmatkesh', 'DEF', 48, 0],
    ['جعفر حسین‌پور', 'Jafar Hosseinpour', 'DEF', 42, 0],
    ['فرزین معامله‌گری', 'Farzin Moamelegari', 'DEF', 45, 0],
    ['علیرضا خوشکفا', 'Alireza Khoshkafa', 'DEF', 40, 0],
    ['محمد پاپی', 'Mohammad Papi', 'MID', 50, 0],
    ['سینا خادم‌پور', 'Sina Khadempour', 'MID', 45, 0],
    ['قائم اسلامی‌خواه', 'Ghaem Eslamikhah', 'MID', 48, 0],
    ['ماهان صادقی', 'Mahan Sadeghi', 'MID', 42, 0],
    ['رضا مرزبان', 'Reza Marzban', 'FWD', 52, 0],
    ['امیررضا کریمی', 'Amirreza Karimi', 'FWD', 45, 0],
    ['فرجاد فیاض', 'Farjad Fayyaz', 'FWD', 40, 0]
  ],
  kheybar: [
    ['محمدرضا دیناروند', 'Mohammadreza Dinarvand', 'GKP', 45, 0],
    ['سبحان پسندیده', 'Sobhan Pasandideh', 'GKP', 40, 0],
    ['مهرداد قنبری', 'Mehrdad Ghanbari', 'DEF', 48, 0],
    ['مسعود محبی', 'Masoud Mohebbi', 'DEF', 42, 0],
    ['عرفان قهرمانی', 'Erfan Ghahremani', 'DEF', 40, 0],
    ['صادق البوصبیح', 'Sadegh Alousabih', 'MID', 50, 1],
    ['فردین یوسفی', 'Fardin Yousefi', 'MID', 45, 0],
    ['اسماعیل بابایی', 'Esmaeil Babaei', 'MID', 52, 0],
    ['ابوذر صفرزاده', 'Abouzar Safarzadeh', 'MID', 42, 0],
    ['امیرحسین فارسی', 'Amirhossein Farsi', 'MID', 45, 0],
    ['احد جمشیدی', 'Ahad Jamshidi', 'FWD', 48, 0],
    ['محمدامین دالوند', 'Mohammadamin Dalvand', 'FWD', 50, 0],
    ['محمدرضا مهدی‌زاده', 'Mohammadreza Mahdizadeh', 'FWD', 48, 0],
    ['علی خانزادی', 'Ali Khanzadi', 'FWD', 40, 0]
  ],
  chadormalou: [
    ['حجت صدقی', 'Hojjat Sedghi', 'GKP', 48, 0],
    ['ادسون ماردن', 'Edson Mardden', 'GKP', 45, 1],
    ['علیرضا آرتا', 'Alireza Arta', 'DEF', 45, 0],
    ['سعید محمدفر', 'Saeid Mohammadifard', 'DEF', 48, 0],
    ['سگوندو پورتوکاررو', 'Segundo Portocarrero', 'DEF', 45, 1],
    ['سیروس صادقیان', 'Sirous Sadeghian', 'DEF', 40, 0],
    ['رضا محمودآبادی', 'Reza Mahmoudabadi', 'MID', 50, 0],
    ['رضا میرزایی', 'Reza Mirzaei', 'MID', 45, 0],
    ['دیگو تورس', 'Diego Torres', 'MID', 52, 1],
    ['ماریو اوتازو', 'Mario Otazu', 'MID', 48, 1],
    ['رنی سیمیسترا', 'Renny Simisterra', 'FWD', 62, 1],
    ['طاها فراهانی', 'Taha Farahani', 'FWD', 42, 0],
    ['ایلیا نگهداری', 'Ilia Negahdari', 'FWD', 40, 0]
  ],
  'esteghlal-khuzestan': [
    ['محمدرضا کیا', 'Mohammadreza Kia', 'GKP', 42, 0],
    ['ابوالفضل سلیمانی', 'Abolfazl Soleimani', 'GKP', 40, 0],
    ['مهدی موسوی', 'Mehdi Mousavi', 'DEF', 45, 0],
    ['آرام عباسی', 'Aram Abbasi', 'DEF', 42, 0],
    ['محمدمهدی احمدی', 'Mohammadmahdi Ahmadi', 'DEF', 40, 0],
    ['حمید بوحمدان', 'Hamid Bou Hamdan', 'MID', 50, 0],
    ['محمد شریفی', 'Mohammad Sharifi', 'MID', 45, 0],
    ['عارف رستمی', 'Aref Rostami', 'MID', 42, 0],
    ['حسین درویشی', 'Hossein Darvishi', 'MID', 40, 0],
    ['محمدمهدی قنبری', 'Mohammadmahdi Ghanbari', 'FWD', 48, 0],
    ['امیرمحمد سیمان‌پور', 'Amirmohammad Simanpour', 'FWD', 42, 0],
    ['جواد زرگان', 'Javad Zargan', 'FWD', 40, 0]
  ],
  'shams-azar': [
    ['مهرشاد اسدی', 'Mehrshad Asadi', 'GKP', 42, 0],
    ['محمدرضا محمدی', 'Mohammadreza Mohammadi', 'GKP', 40, 0],
    ['محمد نژادمهدی', 'Mohammad Nejadmehdi', 'DEF', 45, 0],
    ['ابراهیم مرادی', 'Ebrahim Moradi', 'DEF', 42, 0],
    ['امیررضا کرمی', 'Amirreza Karami', 'DEF', 40, 0],
    ['کیانوش گودرزی', 'Kianoush Goudarzi', 'MID', 48, 0],
    ['مهرداد آقامحمدی', 'Mehrdad Aghamohammadi', 'MID', 42, 0],
    ['علی جلوخانی', 'Ali Joloukhani', 'MID', 40, 0],
    ['رضا محمدی', 'Reza Mohammadi', 'FWD', 50, 0],
    ['مهدی ممی‌زاده', 'Mehdi Memizadeh', 'FWD', 42, 0],
    ['امیرمحمد محکم‌کار', 'Amirmohammad Mohamkar', 'FWD', 40, 0]
  ],
  aluminium: [
    ['محمد خلیفه', 'Mohammad Khalifeh', 'GKP', 45, 0],
    ['ابوالفضل سوختانلو', 'Abolfazl Sookhtanlou', 'GKP', 40, 0],
    ['امیرمحمد هوشمند', 'Amirmohammad Hooshmand', 'DEF', 42, 0],
    ['امیر نوری', 'Amir Noori', 'DEF', 45, 0],
    ['علی رضایی', 'Ali Rezaei', 'DEF', 40, 0],
    ['محمود مطلق‌زاده', 'Mahmoud Motlaghzadeh', 'MID', 45, 0],
    ['منصور باقری', 'Mansour Bagheri', 'MID', 42, 0],
    ['عباس کهریزی', 'Abbas Kahrizi', 'MID', 48, 0],
    ['سید مهدی مهدوی', 'Seyyed Mehdi Mahdavi', 'MID', 40, 0],
    ['شروین بزرگ', 'Shervin Bozorg', 'FWD', 52, 0],
    ['یونس اکبرپور', 'Younes Akbarpour', 'FWD', 45, 0],
    ['رضا جبیره', 'Reza Jabireh', 'FWD', 40, 0]
  ],
  paykan: [
    ['حسین پورحمیدی', 'Hossein Pourhomayouni', 'GKP', 42, 0],
    ['بهزاد سلامی', 'Behzad Salami', 'GKP', 40, 0],
    ['بهزاد سلامی‌نژاد', 'Behzad Salaminejad', 'DEF', 40, 0],
    ['میلاد باقری', 'Milad Bagheri', 'DEF', 42, 0],
    ['صائب محبی', 'Saeb Mohebbi', 'DEF', 42, 0],
    ['صابر حردانی', 'Saber Hardani', 'MID', 45, 0],
    ['مهدی نجفی', 'Mehdi Najafi', 'MID', 42, 0],
    ['ایلیا کرمی', 'Ilia Karami', 'MID', 40, 0],
    ['امید فهمی', 'Omid Fahmi', 'MID', 40, 0],
    ['رضا شکاری‌نو', 'Reza Shekarinou', 'FWD', 45, 0],
    ['فرید امیری', 'Farid Amiri', 'FWD', 45, 0],
    ['عرفان جمشیدی', 'Irfan Jamshidi', 'FWD', 42, 0]
  ],
  'fajr-sepasi': [
    ['علی غلامزاده', 'Ali Gholamzadeh', 'GKP', 45, 0],
    ['میثم مرادی', 'Meysam Moradi', 'GKP', 40, 0],
    ['شاهین توکلی', 'Shahin Tavakoli', 'DEF', 42, 0],
    ['سید مجید نصیری', 'Seyyed Majid Nassiri', 'DEF', 42, 0],
    ['ماهان احمدزاده', 'Mahan Ahmadzadeh', 'DEF', 40, 0],
    ['مسعود ریگی', 'Masoud Rigi', 'MID', 48, 0],
    ['احسان پهلوان', 'Ehsan Pahlevan', 'MID', 45, 0],
    ['یادگار رستمی', 'Yadegar Rostami', 'MID', 42, 0],
    ['مهدی بهرامی‌نژاد', 'Mehdi Bahraminejad', 'MID', 40, 0],
    ['مهدی شریفی', 'Mehdi Sharifi', 'FWD', 48, 0],
    ['حسین شهابی', 'Hossein Shahabi', 'FWD', 42, 0],
    ['ابوالفضل موردی', 'Abolfazl Moordi', 'FWD', 40, 0]
  ],
  nassaji: [
    ['علیرضا جعفرپور', 'Alireza Jafarpour', 'GKP', 45, 0],
    ['امید امیری', 'Omid Amiri', 'GKP', 40, 0],
    ['هومن ربیع‌زاده', 'Hooman Rabizadeh', 'DEF', 42, 0],
    ['ابوالفضل کاظمی', 'Abolfazl Kazemi', 'DEF', 40, 0],
    ['علی آراسته', 'Ali Arasteh', 'DEF', 40, 0],
    ['احمدرضا محمدنژاد', 'Ahmadreza Mohammadnejad', 'MID', 45, 0],
    ['پوریا سرآبادانی', 'Pouria Sarab-adani', 'MID', 42, 0],
    ['آریو مهدوی‌کیا', 'Ario Mahdavikia', 'MID', 45, 0],
    ['علی‌اصغر اعرابی', 'Aliasghar Aarabi', 'MID', 40, 0],
    ['افشین صادقی', 'Afshin Sadeghi', 'FWD', 48, 0],
    ['جواد آقایی‌پور', 'Javad Aghaeipour', 'FWD', 42, 0],
    ['ابوالفضل کوهی', 'Abolfazl Kouhi', 'FWD', 40, 0]
  ],
  'mes-shahrbabak': [
    ['محمدرضا قویدل', 'Mohammadreza Ghavidel', 'GKP', 40, 0],
    ['محسن طرحانی', 'Mohsen Tarhani', 'DEF', 40, 0],
    ['اکبر کربلایی', 'Akbar Karbalaei', 'DEF', 40, 0],
    ['ابوالفضل پوررئیسی', 'Abolfazl Pourraeisi', 'DEF', 40, 0],
    ['فریبرز گرامی', 'Fariborz Gerami', 'DEF', 40, 0],
    ['محمدرضا جوادپورعیوض', 'Mohammadjavad Pouravaz', 'MID', 42, 0],
    ['مجید تاجیک', 'Majid Tajik', 'MID', 42, 0],
    ['محمدامین وهاب‌زاده', 'Mohammadamin Vahabzadeh', 'MID', 40, 0],
    ['رضا جباری', 'Reza Jebbari', 'MID', 40, 0],
    ['علیرضا ولی‌زاده', 'Alireza Valizadeh', 'FWD', 45, 0],
    ['علی جراح', 'Ali Jarragh', 'FWD', 42, 0],
    ['امیر روستایی', 'Amir Roustaei', 'FWD', 42, 0]
  ],
  'sanat-naft': [
    ['احمد گوهری', 'Ahmad Gohari', 'GKP', 42, 0],
    ['دانیال بهرامی‌تبار', 'Danial Bahramitabar', 'GKP', 40, 0],
    ['علی طاهران', 'Ali Taheran', 'DEF', 42, 0],
    ['رضا یزدان‌دوست', 'Reza Yazdandoust', 'DEF', 40, 0],
    ['میثم تیموری', 'Meysam Timouri', 'DEF', 40, 0],
    ['سجاد عساکره', 'Sajjad Asakereh', 'DEF', 40, 0],
    ['طالب ریکانی', 'Taleb Rikani', 'MID', 45, 0],
    ['خشایار زبرجد', 'Khoshayar Zabarjad', 'MID', 42, 0],
    ['بهروز بارانی', 'Behrouz Barani', 'MID', 40, 0],
    ['رضا رضایی', 'Reza Rezaei', 'FWD', 45, 0],
    ['اریک بوکوم', 'Eric Bocoum', 'FWD', 45, 1],
    ['محسن سیفی', 'Mohsen Seifi', 'FWD', 40, 0]
  ]
};
